version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/admin-portal'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions-dependencies:
        patterns:
          - '*'